import { db, leaseDealsTable } from "@workspace/db";

const deals = [
  {
    make: "Honda",
    model: "Civic",
    year: 2025,
    carType: "sedan",
    msrp: "26990",
    monthlyPayment: "199",
    moneyDown: "0",
    termMonths: 36,
    mileageLimit: 10000,
    region: "National",
    trimLevel: "LX",
    description: "One of the best sign and drive deals available. Low monthly on a reliable sedan.",
    expiresAt: new Date("2026-04-30"),
    imageUrl: null,
    sourceUrl: null,
  },
  {
    make: "Toyota",
    model: "Corolla",
    year: 2025,
    carType: "sedan",
    msrp: "24050",
    monthlyPayment: "189",
    moneyDown: "0",
    termMonths: 36,
    mileageLimit: 10000,
    region: "National",
    trimLevel: "LE",
    description: "Toyota reliability at an unbeatable price. True sign and drive deal.",
    expiresAt: new Date("2026-04-30"),
    imageUrl: null,
    sourceUrl: null,
  },
  {
    make: "Kia",
    model: "Niro EV",
    year: 2025,
    carType: "ev",
    msrp: "39600",
    monthlyPayment: "299",
    moneyDown: "0",
    termMonths: 36,
    mileageLimit: 10000,
    region: "National",
    trimLevel: "Wind",
    description: "Federal EV tax credit applied. Go electric for less than 1% MSRP per month.",
    expiresAt: new Date("2026-04-15"),
    imageUrl: null,
    sourceUrl: null,
  },
  {
    make: "Hyundai",
    model: "Elantra",
    year: 2025,
    carType: "sedan",
    msrp: "22500",
    monthlyPayment: "169",
    moneyDown: "0",
    termMonths: 36,
    mileageLimit: 12000,
    region: "National",
    trimLevel: "SE",
    description: "Stunning design and tech features at a steal price. 0.75% MSRP per month.",
    expiresAt: new Date("2026-05-01"),
    imageUrl: null,
    sourceUrl: null,
  },
  {
    make: "Chevrolet",
    model: "Equinox EV",
    year: 2025,
    carType: "ev",
    msrp: "35000",
    monthlyPayment: "299",
    moneyDown: "0",
    termMonths: 36,
    mileageLimit: 10000,
    region: "National",
    trimLevel: "1LT",
    description: "America's most affordable electric SUV. With federal credits applied.",
    expiresAt: new Date("2026-04-30"),
    imageUrl: null,
    sourceUrl: null,
  },
  {
    make: "BMW",
    model: "3 Series",
    year: 2025,
    carType: "sedan",
    msrp: "44900",
    monthlyPayment: "399",
    moneyDown: "0",
    termMonths: 36,
    mileageLimit: 10000,
    region: "National",
    trimLevel: "330i",
    description: "Luxury German performance at sign-and-drive terms. Rare deal on a premium brand.",
    expiresAt: new Date("2026-04-15"),
    imageUrl: null,
    sourceUrl: null,
  },
  {
    make: "Toyota",
    model: "RAV4",
    year: 2025,
    carType: "suv",
    msrp: "32150",
    monthlyPayment: "289",
    moneyDown: "0",
    termMonths: 36,
    mileageLimit: 10000,
    region: "Southeast",
    trimLevel: "XLE",
    description: "America's best-selling SUV at a killer price. Regional deal — Southeast only.",
    expiresAt: new Date("2026-04-20"),
    imageUrl: null,
    sourceUrl: null,
  },
  {
    make: "Nissan",
    model: "Leaf",
    year: 2025,
    carType: "ev",
    msrp: "29900",
    monthlyPayment: "219",
    moneyDown: "0",
    termMonths: 36,
    mileageLimit: 10000,
    region: "National",
    trimLevel: "S Plus",
    description: "Proven EV with real-world range. Under 0.75% MSRP per month.",
    expiresAt: new Date("2026-05-15"),
    imageUrl: null,
    sourceUrl: null,
  },
  {
    make: "Mazda",
    model: "CX-30",
    year: 2025,
    carType: "suv",
    msrp: "27550",
    monthlyPayment: "239",
    moneyDown: "0",
    termMonths: 36,
    mileageLimit: 10000,
    region: "National",
    trimLevel: "2.5 S",
    description: "Premium interior on a budget. Mazda's quality at an unbeatable monthly.",
    expiresAt: new Date("2026-04-30"),
    imageUrl: null,
    sourceUrl: null,
  },
  {
    make: "Ford",
    model: "Mustang Mach-E",
    year: 2025,
    carType: "ev",
    msrp: "43995",
    monthlyPayment: "399",
    moneyDown: "0",
    termMonths: 36,
    mileageLimit: 10000,
    region: "National",
    trimLevel: "Select",
    description: "The iconic Mustang goes electric. Sub-1% MSRP monthly on this sporty EV.",
    expiresAt: new Date("2026-04-30"),
    imageUrl: null,
    sourceUrl: null,
  },
  {
    make: "Subaru",
    model: "Crosstrek",
    year: 2025,
    carType: "suv",
    msrp: "26995",
    monthlyPayment: "249",
    moneyDown: "0",
    termMonths: 36,
    mileageLimit: 10000,
    region: "National",
    trimLevel: "Base",
    description: "AWD all day, every day. Perfect for adventurers who want a deal.",
    expiresAt: new Date("2026-04-30"),
    imageUrl: null,
    sourceUrl: null,
  },
  {
    make: "Volkswagen",
    model: "Jetta",
    year: 2025,
    carType: "sedan",
    msrp: "22995",
    monthlyPayment: "179",
    moneyDown: "0",
    termMonths: 36,
    mileageLimit: 10000,
    region: "National",
    trimLevel: "S",
    description: "German engineering, American pricing. One of the best sedans per dollar.",
    expiresAt: new Date("2026-05-01"),
    imageUrl: null,
    sourceUrl: null,
  },
];

async function seed() {
  console.log("Seeding lease deals...");

  const existing = await db.select().from(leaseDealsTable);
  if (existing.length > 0) {
    console.log(`Database already has ${existing.length} deals. Skipping seed.`);
    process.exit(0);
  }

  for (const deal of deals) {
    await db.insert(leaseDealsTable).values(deal);
    const monthly = Number(deal.monthlyPayment);
    const msrp = Number(deal.msrp);
    const score = ((monthly / msrp) * 100).toFixed(2);
    console.log(`  ✓ ${deal.year} ${deal.make} ${deal.model} — $${deal.monthlyPayment}/mo (${score}% MSRP)`);
  }

  console.log(`\nSeeded ${deals.length} deals successfully!`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
